version: '3.8'

services:
  secure-gateway:
    build: .
    expose:
      - "8000"
    environment:
      - SECRET_ROUTE_PATH=21d85daf-1b8f-4e59-af4f-87fdf84afa90
      - GEMINI_API_KEY=AQ.Ab8RN6KgkyRunvL-5mYezFcuvSN14XH75HBsGmMmuYQmDc4-PA
    restart: always

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"     
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - secure-gateway

volumes:
  caddy_data:
  caddy_config: